[package]
name = "conv-wd"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228" }
serde_json = "1.0.145"
toml = "0.9.10"

[dev-dependencies]
chrono = "0.4.42"
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.23.0"
